#+title: Readme

* References for exact solvers
The best know lower and upper bound can be found in [[./lit/best.csv]].
** [cite:@MendezDiaz06]
** [cite:@Malaguti11]
Main results are from the Branch-and-Price algorithm with the variable branching scheme.

Columns:
- sol_mmt :: the solution computed by the MMT metaheuristic
- t_mmt :: MMT computing time
- mmt_cols :: number of columns generated by the MMT metaheuristic
- tabu_cols :: number of columns generated by the Tabu Algorithm from this article.
- ilp_cols :: number of columns generated by the ILP algorithm
- lb_2400 and ub_2400 :: lower (and upper) bound at the time of 2400s, if not solved earlier.
** [cite:@Held12]
** [cite:@Gualandi12]
The tests are run on a Dell Power
Edge server, using the Linux-Ubuntu server edition
(64 bits), two processors with four cores, and 4 GB
of memory; the codes have been compiled with a
gnu-g++ compiler (version 4.3). The results on our
server of the dfmax benchmark used in the challenge
to compare machines are r200.5: 0.04s r300.5: 0.37s,
r400.5: 2.30s, and r500.5: 8.74s.

Only the "hardest" instances
** [cite:@Morrison16]
Intel Core
i7-930 2.8 GHz quad-core processor and 12GB ram

dfmax benchmark program was
run on the r500.5 instance provided by Trick (2005). The
computer used for these experiments took 6.60 s CPU
(central processing unit) time to solve this benchmark
instance.

- t_z :: Time needed to construct the maximal independent set ZDD
- t :: Time spent in the branch-and-price phase of the algorithm
- t_mmt_init :: Total initialization time used by Malaguti et al. (2011)
- t_mmt :: Adjusted time to verify optimality by Malaguti et al. (2011)
- t_wide :: Adjusted time to verify optimality by the wide branching solver of [cite:@Morrison14]
- t_cp_bnp :: Adjusted time to verify optimality by the branch-and-price solver of [cite:@Ferrarini22]
** [cite:@Cornaz17]
IntelXeonE3-1220processorat3.10GHzand8GBRAM.
time limit = 6.5h

rep_{lb, ub, time} are the results for the Representatives formulation by [cite:@Campelo08].
** [cite:@Ternier17]
All the algorithms are coded in C/C++, and run on a PC with an Intel(R) Core(TM)
i7-4770 CPU at 3.40GHz and 16 GB RAM memory, under Linux Ubuntu 14.04 64-bit.

Time limit of 3600s
** [cite:@Jabrayilov18; @Jabrayilov22]
For the 2018 results, the [[./lit/jabrayilov18.csv.csv]] has the results for the POP2 model.
Intel Core i7-4790, 3.6GHz, with 32 GB of memory and running Ubuntu Linux 14.04.

For the 2022 results, the [[./lit/jabrayilov22.csv]] has the results for the POPH2 model.
Gurobi 6.5 single-threadedly on the machine with Intel E5-2640@2.60GHz running Ubuntu 18.04

** [cite:@Hoeve21]
[[./lit/hoeve21-table1.csv]] has the comparison between the relaxed and exact decision diagram (the former performs better).
[[./lit/hoeve21-table2.csv]] has the best results they could manage with different configurations. Also, it serves as a benchmark for the results of the DSATUR heuristic.
[[./lit/hoeve21-table3.csv]] has the comparison between the [cite:@Held12] of [cite:@Mehrotra96] and their best configuration.

Relaxed Diagram can find optimal in more instances in less time (table 1).
The best ordering are the Max-Connected-Degree and DSATUR ordering (table 2).
They also ran the [cite:@Held12] implementation on they machine: Held's solves more instances to optimal, but DD can return an LB in all instances.
  # TODO mas esse LB é melhor que o cliquer?

Their results where obtained on a Intel Xeon E5345 @ 2.33 Ghz
** [cite:@Heule22]
Uses an alternating Max Clique and Graph Coloring SAT solvers.
The reported time is the average of 128 seeds on a AMD EPYC 7742.
Using an Intel Xeon @ 2.33GHz, they proved optimal for 83 instances.

The csv can be found in [[./lit/heule22.csv]].
